const PRODUCTS = [

  // ══════════════ Atalanta (Serie A) ══════════════
  { id: 1, name: "Maglia Atalanta Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2025/26. Azzurro brillante con dettagli premium.", inStock: true },
  { id: 2, name: "Maglia Atalanta Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta dell'Atalanta 2025/26. Bianco brillante con dettagli premium.", inStock: true },
  { id: 3, name: "Maglia Atalanta Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Atalanta 2025/26. Arancio brillante con dettagli premium.", inStock: true },
  { id: 4, name: "Maglia Atalanta Christmas Edition 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 25.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Christmas 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale dell'Atalanta 2025/26. Azzurro brillante con dettagli premium.", inStock: true },
  { id: 5, name: "Maglia Atalanta Goalkeeper kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 25.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta 1P 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La prima maglia da portiere dell'Atalanta 2025/26. Verde brillante con dettagli premium.", inStock: true },
  { id: 6, name: "Maglia Atalanta Uefa Super Cup 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 30.00, oldPrice: null, badge: "finali europee", badgeLabel: "vintage", image: "images/3d/Serie A/Atalanta/speciali/Atalanta Uefaa Super Cup 2425.jpg", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della finale di Uefa Super Cup dell'Atalanta 2024/25.", inStock: true },
  { id: 7, name: "Maglia Atalanta Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2425/Atalanta Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2024/25. Azzurro brillante con dettagli premium.", inStock: true },
  { id: 8, name: "Maglia Atalanta Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2425/Atalanta Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta dell'Atalanta 2024/25. Bianco brillante con dettagli premium.", inStock: true },
  { id: 9, name: "Maglia Atalanta Europa League Final 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 30.00, oldPrice: null, badge: "finali europee", badgeLabel: "vintage", image: "images/3d/Serie A/Atalanta/speciali/Atalanta Europe Final 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della finale di Europa League dell'Atalanta 2023/24.", inStock: true },
  { id: 10, name: "Maglia Atalanta Home 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2223/Atalanta Home 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2022/23. Azzurro brillante con dettagli premium.", inStock: true },

  // ══════════════ Bologna (Serie A) ════════════
  { id: 11, name: "Maglia Bologna Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2025/26.", inStock: true },
  { id: 12, name: "Maglia Bologna Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Bologna 2025/26.", inStock: true },
  { id: 13, name: "Maglia Bologna Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Atalanta 2025/26.", inStock: true },
  { id: 14, name: "Maglia Bologna Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2024/25.", inStock: true },
  { id: 15, name: "Maglia Bologna Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Bologna 2024/25", inStock: true },
  { id: 16, name: "Maglia Bologna Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Bologna 2024/25.", inStock: true },
  { id: 17, name: "Maglia Bologna Special Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Fourth 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale del Bologna 2024/25.", inStock: true },
  { id: 18, name: "Maglia Bologna 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2324/Bologna Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2023/24.", inStock: true },

  // ══════════════ Cagliari (Serie A) ══════════════
  { id: 19, name: "Maglia Cagliari Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Cagliari 2025/26.", inStock: true },
  { id: 20, name: "Maglia Cagliari Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Cagliari 2025/26.", inStock: true },
  { id: 21, name: "Maglia Cagliari Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Cagliari 2025/26.", inStock: true },

  // ══════════════ Como (Serie A) ══════════════
  { id: 22, name: "Maglia Como Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "images/3d/Serie A/Como/2627/Como Home 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Como 2026/27.", inStock: true },
  { id: 23, name: "Maglia Como Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Como 2025/26.", inStock: true },
  { id: 24, name: "Maglia Como Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Como 2025/26.", inStock: true },
  { id: 25, name: "Maglia Como Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Como 2025/26.", inStock: true },
  { id: 26, name: "Maglia Como Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Home 2425.png", sizes: ["XS", "S", "M", "L", ("XL"), ("XXL")], description: "La maglia casalinga del Como 2024/25.", inStock: true },
  { id: 27, name: "Maglia Como Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Como 2024/25.", inStock: true },
  { id: 28, name: "Maglia Como Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Como 2024/25.", inStock: true },

  // ══════════════ Cremonese (Serie A) ══════════════
  { id: 29, name: "Maglia Cremonese Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cremonese/2526/Cremonese Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Cremonese 2025/26.", inStock: true },
  { id: 30, name: "Maglia Cremonese Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cremonese/2425/Cremonese Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Cremonese 2024/25.", inStock: true },

  //Fiorentina (Serie A) ══════════════
  { id: 31, name: "Maglia Fiorentina Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/2526/Fiorentina Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Fiorentina 2025/26.", inStock: true },
  { id: 32, name: "Maglia Fiorentina Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/2526/Fiorentina Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Fiorentina 2025/26.", inStock: true },
  { id: 33, name: "Maglia Fiorentina Home 1998/99", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/speciali/Fiorentina Home 9899.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La storica maglia casalinga della Fiorentina 1998/99.", inStock: true },

  //Genoa (Serie A) ══════════════
  { id: 34, name: "Maglia Genoa Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/2526/Genoa Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Genoa 2025/26.", inStock: true },
  { id: 35, name: "Maglia Genoa Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/speciali/Genoa Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Genoa 2024/25.", inStock: true },
  { id: 36, name: "Maglia Genoa Special 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/speciali/Genoa Fourth 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La quarta maglia del Genoa 2024/25.", inStock: true },

  // ══════════════ Inter (Serie A) ══════════════

  // ══════════════ Juve (Serie A) ══════════════

  // ══════════════ Lazio (Serie A) ══════════════
  { id: 37, name: "Maglia Lazio Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Lazio 2025/26.", inStock: true },
  { id: 38, name: "Maglia Lazio Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Lazio 2025/26.", inStock: true },
  { id: 39, name: "Maglia Lazio Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Lazio 2025/26.", inStock: true },
  { id: 40, name: "Maglia Lazio Coppa Italia Semifinal 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Semifinal Coppa Italia 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della semifinale di coppa italia della Lazio 2025/26.", inStock: true },
  { id: 41, name: "Maglia Lazio Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Lazio 2024/25.", inStock: true },
  { id: 42, name: "Maglia Lazio Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Lazio 2024/25.", inStock: true },
  { id: 43, name: "Maglia Lazio Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Lazio 2024/25.", inStock: true },
  { id: 44, name: "Maglia Lazio Fourth Kit 2014/15", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Lazio/Speciali/Lazio Fourth 1415.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale della Lazio 2014/15.", inStock: true },
  { id: 45, name: "Maglia Lazio Uefa Super Cup 1999/00", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Lazio/Speciali/Lazio Uefa SuperCup 1999-00.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale della Uefa Super Cup della Lazio 1999/00.", inStock: true },

  // ══════════════ Lecce (Serie A) ══════════════
  { id: 46, name: "Maglia Lecce Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lecce/2526/Lecce Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Lecce 2025/26.", inStock: true },

  // ══════════════ Milan (Serie A) ══════════════

  // ══════════════ Napoli (Serie A) ══════════════
  { id: 47, name: "Maglia Napoli Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2025/26.", inStock: true },
  { id: 48, name: "Maglia Napoli Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Napoli 2025/26.", inStock: true },
  { id: 49, name: "Maglia Napoli Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa del Napoli 2025/26.", inStock: true },
  { id: 50, name: "Maglia Napoli Halloween 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Halloween 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia edizione Halloween del Napoli 2025/26.", inStock: true },
  { id: 51, name: "Maglia Napoli Away Champions League 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Away Champions 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta di Champions League del Napoli 2025/26.", inStock: true },
  { id: 52, name: "Maglia Napoli Third Kit Champions League 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Third Champions 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa di Champions League del Napoli 2025/26.", inStock: true },
  { id: 53, name: "Maglia Napoli PreMatch-1 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli PreMatch 1 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La prima maglia PreMatch del Napoli 2025/26.", inStock: true },
  { id: 54, name: "Maglia Napoli PreMatch-2 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli PreMatch 2 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La seconda maglia PreMatch del Napoli 2025/26.", inStock: true },
  { id: 55, name: "Maglia Napoli Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2425/Napoli Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2024/25.", inStock: true },
  { id: 56, name: "Maglia Napoli Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2425/Napoli Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Napoli 2024/25.", inStock: true },
  { id: 57, name: "Maglia Napoli Home 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia PreMatch 5 del Napoli 2025/26.", inStock: true },
  { id: 58, name: "Maglia Napoli Away 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Away 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia PreMatch 6 del Napoli 2025/26.", inStock: true },
  { id: 59, name: "Maglia Napoli Third Kit 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Third 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2024/25.", inStock: true },
  { id: 60, name: "Maglia Napoli PreMatch 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Prematch 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Roma 2024/25.", inStock: true },
  { id: 61, name: "Maglia Napoli Training 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Training 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2024/25.", inStock: true },
  { id: 62, name: "Maglia Napoli Home 1987/88", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Napoli/Napoli Home 198788.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Pisa 2025/26.", inStock: true },

  // ══════════════ Parma (Serie A) ══════════════
  { id: 63, name: "Maglia Parma Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Parma/2526/Parma Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Parma 2025/26.", inStock: true },

  // ══════════════ Pisa (Serie B) ══════════════
  { id: 64, name: "Maglia Pisa Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Pisa/2526/Pisa Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Pisa 2025/26.", inStock: true },

  // ══════════════ Roma (Serie A) ══════════════
  { id: 65, name: "Maglia Roma Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2025/26.", inStock: true },
  { id: 66, name: "Maglia Roma Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2025/26.", inStock: true },
  { id: 67, name: "Maglia Roma Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2025/26.", inStock: true },
  { id: 68, name: "Maglia Roma Prematch 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma PreMatch 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia prematch della Roma 2025/26.", inStock: true },
  { id: 69, name: "Maglia Roma Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2024/25.", inStock: true },
  { id: 70, name: "Maglia Roma Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2024/25.", inStock: true },
  { id: 71, name: "Maglia Roma Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2024/25.", inStock: true },
  { id: 72, name: "Maglia Roma Home 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2023/24.", inStock: true },
  { id: 73, name: "Maglia Roma Away 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Away 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2023/24.", inStock: true },
  { id: 74, name: "Maglia Roma Third Kit 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Third 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2023/24.", inStock: true },
  { id: 75, name: "Maglia Roma Fourth Kit 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Fourth 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della quarta divisa della Roma 2023/24.", inStock: true },
  { id: 76, name: "Maglia Roma Home 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Home 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 1983/84.", inStock: true },
  { id: 77, name: "Maglia Roma Away 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Away 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 1983/84.", inStock: true },
  { id: 78, name: "Maglia Roma Third Kit 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Third 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 1983/84.", inStock: true },
  { id: 79, name: "Maglia Roma Europa League Edition 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 26.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/2223/Roma Special Europa 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della quarta divisa della Roma 1983/84.", inStock: true },
  { id: 80, name: "Maglia Roma Home da definire", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/Roma.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 1983/84.", inStock: true },
  { id: 81, name: "Maglia Roma Home da definire", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/Romaa.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 1983/84.", inStock: true },

  // ══════════════ Sassuolo (Serie A) ══════════════
  { id: 82, name: "Maglia Sassuolo Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Sassuolo/2526/Sassuolo Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Sassuolo 2025/26.", inStock: true },

  // ══════════════ Torino (Serie A) ══════════════
  { id: 83, name: "Maglia Torino Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Torino/2526/Torino Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Torino 2025/26.", inStock: true },

  // ══════════════ Udinese (Serie A) ══════════════

  // ══════════════ Verona (Serie A) ══════════════


  //La liga 
  // ══════════════ BARCELLONA ══════════════
  { id: 42, name: "Maglia Barcellona Special 2026/27", category: "La Liga", categoryLabel: "La Liga", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/La Liga/Barcellona/Speciali/Barca Special 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La special blaugrana del Barcellona 2026/27. Tessuto tecnico Dri-FIT.", inStock: true },
  { id: 43, name: "Maglia Barcellona Home 2025/26", category: "La Liga", categoryLabel: "La Liga", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/La Liga/Barcellona/Barca Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La classica blaugrana del Barcellona 2025/26. Tessuto tecnico Dri-FIT.", inStock: true },
  { id: 44, name: "Maglia Barcellona Special 2025/26", category: "La Liga", categoryLabel: "La Liga", price: 22.00, oldPrice: null, badge: "sale", badgeLabel: "13% OFF", image: "images/3d/La Liga/Barcellona/Speciali/Barca Special 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Barcellona 2025/26.", inStock: true },



  // ══════════════ ATLETICO MADRID ══════════════
  { id: 45, name: "Maglia Atletico Madrid Home 2025/26", category: "Champions", categoryLabel: "Champions League", price: 85.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/atletico_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Atletico Madrid 2025/26. Strisce bianche e rosse iconiche.", inStock: true },
  { id: 46, name: "Maglia Atletico Madrid Away 2025/26", category: "Champions", categoryLabel: "Champions League", price: 80.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/atletico_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Atletico Madrid 2025/26.", inStock: true },

  // ══════════════ PORTO ══════════════
  { id: 47, name: "Maglia Porto Home 2025/26", category: "Champions", categoryLabel: "Champions League", price: 75.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/porto_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Porto 2025/26. Blu e bianco.", inStock: true },

  // ══════════════ MANCHESTER CITY (Premier League) ══════════════
  { id: 48, name: "Maglia Manchester City Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 95.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/mancity_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Manchester City 2025/26. Azzurro cielo con sponsor Puma.", inStock: true },
  { id: 49, name: "Maglia Manchester City Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 90.00, oldPrice: 105.00, badge: "sale", badgeLabel: "14% OFF", image: "images/teams/mancity_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Manchester City 2025/26. Design bianco elegante.", inStock: true },

  // ══════════════ ARSENAL ══════════════
  { id: 50, name: "Maglia Arsenal Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 92.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/arsenal_home.png", sizes: ["XS", "S", "M", "L", ("XL"), ("XXL")], description: "La classica maglia rossa dell'Arsenal 2025/26. Adidas con dettagli bianchi.", inStock: true },
  { id: 51, name: "Maglia Arsenal Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 88.00, oldPrice: 100.00, badge: "sale", badgeLabel: "12% OFF", image: "images/teams/arsenal_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Arsenal 2025/26. Bianco con dettagli rossi.", inStock: true },
  { id: 26, name: "Maglia Liverpool Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 94.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/liverpool_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Liverpool 2025/26. Rosso intenso con logo LFC ricamato.", inStock: true },
  { id: 27, name: "Maglia Liverpool Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 88.00, oldPrice: 100.00, badge: "sale", badgeLabel: "12% OFF", image: "images/teams/liverpool_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Liverpool 2025/26. Verde menta con dettagli rossi.", inStock: true },

  // ══════════════ CHELSEA ══════════════
  { id: 28, name: "Maglia Chelsea Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 90.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/chelsea_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Chelsea 2025/26. Blu reale con logo CFC.", inStock: true },
  { id: 29, name: "Maglia Chelsea Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 85.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/chelsea_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Chelsea 2025/26. Bianco con bordi blu.", inStock: true },

  // ══════════════ MANCHESTER UNITED ══════════════
  { id: 30, name: "Maglia Manchester United Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 93.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/manutd_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Manchester United 2025/26. Rosso iconico con logo diavolo.", inStock: true },
  { id: 31, name: "Maglia Manchester United Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 88.00, oldPrice: 100.00, badge: "sale", badgeLabel: "12% OFF", image: "images/teams/manutd_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Manchester United 2025/26. Bianco con dettagli neri.", inStock: true },

  // ══════════════ TOTTENHAM ══════════════
  { id: 32, name: "Maglia Tottenham Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 86.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/tottenham_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Tottenham 2025/26. Bianco con gallo ricamato.", inStock: true },

  // ══════════════ NEWCASTLE ══════════════
  { id: 33, name: "Maglia Newcastle Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 84.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/newcastle_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Newcastle 2025/26. Strisce bianco-nere iconiche.", inStock: true },

  // ══════════════ BORUSSIA DORTMUND ══════════════
  { id: 46, name: "Maglia Borussia Dortmund Home 2025/26", category: ["Champions", "Bundesliga"], categoryLabel: ["Champions League", "Bundesliga"], price: 88.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/dortmund_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga BVB 2025/26. Giallo-nero iconico di Dortmund.", inStock: true },
  { id: 47, name: "Maglia Borussia Dortmund Away 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 83.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/dortmund_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta BVB 2025/26. Nero con dettagli gialli.", inStock: true },

  // ══════════════ BAYERN MONACO ══════════════
  { id: 48, name: "Maglia Bayern Monaco Home 2025/26", category: ["Champions", "Bundesliga"], categoryLabel: ["Champions League", "Bundesliga"], price: 92.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/jersey_germany.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Bayern Monaco 2025/26. Rosso Adidas con stemma ricamato.", inStock: true },
  { id: 49, name: "Maglia Bayern Monaco Away 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 87.00, oldPrice: 100.00, badge: "sale", badgeLabel: "13% OFF", image: "images/teams/bayern_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Bayern Monaco 2025/26. Bianco con bordi rossi.", inStock: true },

  // ══════════════ BAYER LEVERKUSEN ══════════════
  { id: 50, name: "Maglia Bayer Leverkusen Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 82.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/leverkusen_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Bayer Leverkusen 2025/26. Rosso-nero dei campioni.", inStock: true },

  // ══════════════ RB LEIPZIG ══════════════
  { id: 51, name: "Maglia RB Leipzig Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 80.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/leipzig_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga RB Leipzig 2025/26. Bianco e rosso con Nike.", inStock: true },

  // ══════════════ EINTRACHT FRANCOFORTE ══════════════
  { id: 52, name: "Maglia Eintracht Francoforte Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 78.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/eintracht_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Eintracht Francoforte 2025/26. Bianco-nero-rosso.", inStock: true },

  // ══════════════ AL NASSR (Saudi Pro League) ══════════════
  { id: 53, name: "Maglia Al Nassr Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 75.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/alnassr_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia di Cristiano Ronaldo! Al Nassr Home 2025/26. Giallo e blu iconici.", inStock: true },
  { id: 54, name: "Maglia Al Nassr Away 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 70.00, oldPrice: 85.00, badge: "sale", badgeLabel: "18% OFF", image: "images/teams/alnassr_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Al Nassr 2025/26 — la squadra di CR7. Bianco con dettagli blu.", inStock: true },
  { id: 55, name: "Maglia Al Nassr CR7 Edition 2025", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 99.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/teams/alnassr_cr7.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione speciale Al Nassr con il numero 7 di Cristiano Ronaldo. Collezione limitata.", inStock: true },

  // ══════════════ AL HILAL ══════════════
  { id: 56, name: "Maglia Al Hilal Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 72.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alhilal_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Hilal 2025/26. Blu con mezzaluna ricamata.", inStock: true },
  { id: 57, name: "Maglia Al Hilal Away 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 68.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alhilal_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Al Hilal 2025/26. Bianco con dettagli blu.", inStock: true },

  // ══════════════ AL ITTIHAD ══════════════
  { id: 58, name: "Maglia Al Ittihad Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 70.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alittihad_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Ittihad 2025/26. Strisce giallo-nere.", inStock: true },

  // ══════════════ AL AHLI ══════════════
  { id: 59, name: "Maglia Al Ahli Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 68.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alahli_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Ahli 2025/26. Verde con dettagli bianchi.", inStock: true },

  // ══════════════ AL QADSIAH ══════════════
  { id: 60, name: "Maglia Al Qadsiah Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 65.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alqadsiah_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Qadsiah 2025/26.", inStock: true },

];
