const PRODUCTS = [
  // ══════════════ Atalanta (Serie A) ══════════════
  { id: 184, name: "Maglia Atalanta Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "images/3d/Serie A/Atalanta/2627/Atalanta Home 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2026/27.", kitType: 'solo', inStock: true },
  { id: 1, name: "Maglia Atalanta Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2025/26. Azzurro brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 2, name: "Maglia Atalanta Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta dell'Atalanta 2025/26. Bianco brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 3, name: "Maglia Atalanta Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Atalanta 2025/26. Arancio brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 4, name: "Maglia Atalanta Christmas Edition 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 25.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta Christmas 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale dell'Atalanta 2025/26. Azzurro brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 5, name: "Maglia Atalanta Goalkeeper kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 25.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2526/Atalanta 1P 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La prima maglia da portiere dell'Atalanta 2025/26. Verde brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 6, name: "Maglia Atalanta Uefa Super Cup 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 30.00, oldPrice: null, badge: "finali europee", badgeLabel: "vintage", image: "images/3d/Serie A/Atalanta/speciali/Atalanta Uefaa Super Cup 2425.jpg", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della finale di Uefa Super Cup dell'Atalanta 2024/25.", kitType: 'solo', inStock: true },
  { id: 7, name: "Maglia Atalanta Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2425/Atalanta Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2024/25. Azzurro brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 8, name: "Maglia Atalanta Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2425/Atalanta Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta dell'Atalanta 2024/25. Bianco brillante con dettagli premium.", kitType: 'solo', inStock: true },
  { id: 9, name: "Maglia Atalanta Europa League Final 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 30.00, oldPrice: null, badge: "finali europee", badgeLabel: "vintage", image: "images/3d/Serie A/Atalanta/speciali/Atalanta Europe Final 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della finale di Europa League dell'Atalanta 2023/24.", kitType: 'solo', inStock: true },
  { id: 10, name: "Maglia Atalanta Home 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Atalanta/2223/Atalanta Home 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atalanta 2022/23. Azzurro brillante con dettagli premium.", kitType: 'solo', inStock: true },

  // ══════════════ Bologna (Serie A) ════════════
  { id: 11, name: "Maglia Bologna Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2025/26.", kitType: 'solo', inStock: true },
  { id: 12, name: "Maglia Bologna Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Bologna 2025/26.", kitType: 'solo', inStock: true },
  { id: 13, name: "Maglia Bologna Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2526/Bologna Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Atalanta 2025/26.", kitType: 'solo', inStock: true },
  { id: 14, name: "Maglia Bologna Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2024/25.", kitType: 'solo', inStock: true },
  { id: 15, name: "Maglia Bologna Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Bologna 2024/25", kitType: 'solo', inStock: true },
  { id: 16, name: "Maglia Bologna Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Bologna 2024/25.", kitType: 'solo', inStock: true },
  { id: 17, name: "Maglia Bologna Special Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2425/Bologna Fourth 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale del Bologna 2024/25.", kitType: 'solo', inStock: true },
  { id: 18, name: "Maglia Bologna 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Bologna/2324/Bologna Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2023/24.", kitType: 'solo', inStock: true },

  // ══════════════ Cagliari (Serie A) ══════════════
  { id: 19, name: "Maglia Cagliari Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Cagliari 2025/26.", kitType: 'solo', inStock: true },
  { id: 20, name: "Maglia Cagliari Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Cagliari 2025/26.", kitType: 'solo', inStock: true },
  { id: 21, name: "Maglia Cagliari Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cagliari/2526/Cagliari Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Cagliari 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Como (Serie A) ══════════════
  { id: 22, name: "Maglia Como Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "images/3d/Serie A/Como/2627/Como Home 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Como 2026/27.", kitType: 'solo', inStock: true },
  { id: 23, name: "Maglia Como Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Como 2025/26.", kitType: 'solo', inStock: true },
  { id: 24, name: "Maglia Como Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Como 2025/26.", kitType: 'solo', inStock: true },
  { id: 25, name: "Maglia Como Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2526/Como Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Como 2025/26.", kitType: 'solo', inStock: true },
  { id: 26, name: "Maglia Como Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Home 2425.png", sizes: ["XS", "S", "M", "L", ("XL"), ("XXL")], description: "La maglia casalinga del Como 2024/25.", kitType: 'solo', inStock: true },
  { id: 27, name: "Maglia Como Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Como 2024/25.", kitType: 'solo', inStock: true },
  { id: 28, name: "Maglia Como Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Como/2425/Como Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Como 2024/25.", kitType: 'solo', inStock: true },

  // ══════════════ Cremonese (Serie A) ══════════════
  { id: 29, name: "Maglia Cremonese Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cremonese/2526/Cremonese Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Cremonese 2025/26.", kitType: 'solo', inStock: true },
  { id: 30, name: "Maglia Cremonese Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Cremonese/2425/Cremonese Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Cremonese 2024/25.", kitType: 'solo', inStock: true },

  //Fiorentina (Serie A) ══════════════
  { id: 31, name: "Maglia Fiorentina Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/2526/Fiorentina Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Fiorentina 2025/26.", kitType: 'solo', inStock: true },
  { id: 32, name: "Maglia Fiorentina Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/2526/Fiorentina Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Fiorentina 2025/26.", kitType: 'solo', inStock: true },
  { id: 33, name: "Maglia Fiorentina Home 1998/99", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Fiorentina/speciali/Fiorentina Home 9899.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La storica maglia casalinga della Fiorentina 1998/99.", kitType: 'solo', inStock: true },

  //Genoa (Serie A) ══════════════
  { id: 34, name: "Maglia Genoa Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/2526/Genoa Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Genoa 2025/26.", kitType: 'solo', inStock: true },
  { id: 35, name: "Maglia Genoa Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/speciali/Genoa Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Genoa 2024/25.", kitType: 'solo', inStock: true },
  { id: 36, name: "Maglia Genoa Special 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Genoa/speciali/Genoa Fourth 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La quarta maglia del Genoa 2024/25.", kitType: 'solo', inStock: true },

  // ══════════════ Inter (Serie A) ══════════════
  { id: 185, name: "Maglia Inter Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Inter Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Inter 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════ Juve (Serie A) ══════════════

  // ══════════════ Lazio (Serie A) ══════════════
  { id: 187, name: "Maglia Lazio Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "images/3d/Serie A/Lazio/2627/Lazio Home 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Lazio 2026/27.", kitType: 'solo', inStock: true },
  { id: 37, name: "Maglia Lazio Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Lazio 2025/26.", kitType: 'solo', inStock: true },
  { id: 38, name: "Maglia Lazio Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Lazio 2025/26.", kitType: 'solo', inStock: true },
  { id: 39, name: "Maglia Lazio Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Lazio 2025/26.", kitType: 'solo', inStock: true },
  { id: 40, name: "Maglia Lazio Coppa Italia Semifinal 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2526/Lazio Semifinal Coppa Italia 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della semifinale di coppa italia della Lazio 2025/26.", kitType: 'solo', inStock: true },
  { id: 41, name: "Maglia Lazio Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Lazio 2024/25.", kitType: 'solo', inStock: true },
  { id: 42, name: "Maglia Lazio Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Lazio 2024/25.", kitType: 'solo', inStock: true },
  { id: 43, name: "Maglia Lazio Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lazio/2425/Lazio Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Lazio 2024/25.", kitType: 'solo', inStock: true },
  { id: 44, name: "Maglia Lazio Fourth Kit 2014/15", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Lazio/Speciali/Lazio Fourth 1415.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale della Lazio 2014/15.", kitType: 'solo', inStock: true },
  { id: 45, name: "Maglia Lazio Uefa Super Cup 1999/00", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Lazio/Speciali/Lazio Uefa SuperCup 1999-00.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale della Uefa Super Cup della Lazio 1999/00.", kitType: 'solo', inStock: true },

  // ══════════════ Lecce (Serie A) ══════════════
  { id: 46, name: "Maglia Lecce Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Lecce/2526/Lecce Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Lecce 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Inter (Serie A) ══════════════
  { id: 47, name: "Terza Maglia Inter 1997/98", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/terza maglia inter 9798.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La leggendaria terza maglia dell'Inter stagione 1997/98.", kitType: 'solo', inStock: true },
  { id: 48, name: "Maglia Inter Finale Champions League 2008/09", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/maglia inter finale champions 2009.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia indossata dall'Inter nella finale di Champions League 2008/09. Edizione storica.", kitType: 'solo', inStock: true },
  { id: 49, name: "Tuta Inter 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 40.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/tuta inter 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La tuta ufficiale dell'Inter stagione 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Juventus (Serie A) ═════════════
  { id: 186, name: "Maglia Juventus Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Juventus Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Juventus 2026/27.", kitType: 'solo', inStock: true },
  { id: 50, name: "Maglia Juventus Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/Serie A/-Juventus/ChatGPT Image 29 apr 2026, 01_51_03.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Juventus 2025/26.", kitType: 'solo', inStock: true },
  { id: 51, name: "Maglia Juventus Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/Serie A/-Juventus/ChatGPT Image 29 apr 2026, 01_58_08.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Juventus 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Milan (Serie A) ══════════════
  { id: 188, name: "Maglia Milan Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Milan Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Milan 2026/27.", kitType: 'solo', inStock: true },


  // ══════════════ Napoli (Serie A) — Sponsor tecnico: EA7 ══════════════
  { id: 189, name: "Maglia Napoli Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Napoli Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2026/27.", kitType: 'solo', inStock: true },
  { id: 52, name: "Maglia Napoli Home 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 53, name: "Maglia Napoli Away 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 54, name: "Maglia Napoli Third Kit 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 55, name: "Maglia Napoli Halloween 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Halloween 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia edizione Halloween del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 56, name: "Maglia Napoli Away Champions League 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Away Champions 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta di Champions League del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 57, name: "Maglia Napoli Third Kit Champions League 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli Third Champions 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa di Champions League del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 58, name: "Maglia Napoli PreMatch-1 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli PreMatch 1 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La prima maglia PreMatch del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 59, name: "Maglia Napoli PreMatch-2 2025/26", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2526/Napoli PreMatch 2 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La seconda maglia PreMatch del Napoli 2025/26.", kitType: 'solo', inStock: true },
  { id: 60, name: "Maglia Napoli Home 2024/25", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2425/Napoli Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2024/25.", kitType: 'solo', inStock: true },
  { id: 61, name: "Maglia Napoli Away 2024/25", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2425/Napoli Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Napoli 2024/25.", kitType: 'solo', inStock: true },
  { id: 62, name: "Maglia Napoli Home 2023/24", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Napoli 2023/24.", kitType: 'solo', inStock: true },
  { id: 63, name: "Maglia Napoli Away 2023/24", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Away 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Napoli 2023/24.", kitType: 'solo', inStock: true },
  { id: 64, name: "Maglia Napoli Third Kit 2023/24", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Third 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Napoli 2023/24.", kitType: 'solo', inStock: true },
  { id: 65, name: "Maglia Napoli PreMatch 2023/24", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Prematch 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia PreMatch del Napoli 2023/24.", kitType: 'solo', inStock: true },
  { id: 66, name: "Maglia Napoli Training 2023/24", brand: "EA7", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Napoli/2324/Napoli Training 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da allenamento del Napoli 2023/24.", kitType: 'solo', inStock: true },
  { id: 67, name: "Maglia Napoli Home 1987/88", brand: "Ennerre", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Napoli/Napoli Home 198788.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La storica maglia casalinga del Napoli 1987/88, l'anno dello scudetto con Maradona.", kitType: 'solo', inStock: true },

  // ══════════════ Parma (Serie A) ══════════════
  { id: 68, name: "Maglia Parma Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Parma/2526/Parma Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Parma 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Pisa (Serie B) ══════════════
  { id: 69, name: "Maglia Pisa Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Pisa/2526/Pisa Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Pisa 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Roma (Serie A) ══════════════
  { id: 190, name: "Maglia Roma Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "images/3d/Serie A/Roma/2627/Roma Home 2627.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2026/27.", kitType: 'solo', inStock: true },
  { id: 70, name: "Maglia Roma Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2025/26.", shortsProductId: 82, kitType: 'solo', inStock: true },
  { id: 71, name: "Maglia Roma Away 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Away 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2025/26.", kitType: 'solo', inStock: true },
  { id: 72, name: "Maglia Roma Third Kit 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2025/26.", kitType: 'solo', inStock: true },
  { id: 73, name: "Maglia Roma Prematch 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Roma PreMatch 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia prematch della Roma 2025/26.", kitType: 'solo', inStock: true },
  { id: 74, name: "Maglia Roma Home 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Home 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2024/25.", kitType: 'solo', inStock: true },
  { id: 75, name: "Maglia Roma Away 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Away 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2024/25.", kitType: 'solo', inStock: true },
  { id: 76, name: "Maglia Roma Third Kit 2024/25", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2425/Roma Third 2425.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2024/25.", kitType: 'solo', inStock: true },
  { id: 77, name: "Maglia Roma Home 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Home 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 2023/24.", kitType: 'solo', inStock: true },
  { id: 78, name: "Maglia Roma Away 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Away 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 2023/24.", kitType: 'solo', inStock: true },
  { id: 79, name: "Maglia Roma Third Kit 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Third 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 2023/24.", kitType: 'solo', inStock: true },
  { id: 80, name: "Maglia Roma Fourth Kit 2023/24", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2324/Roma Fourth 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della quarta divisa della Roma 2023/24.", kitType: 'solo', inStock: true },
  { id: 81, name: "Maglia Roma Home 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Home 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 82, name: "Maglia Roma Away 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Away 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 83, name: "Maglia Roma Third Kit 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 22.00, oldPrice: null, badge: "null", badgeLabel: "null", image: "images/3d/Serie A/Roma/2223/Roma Third 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della terza divisa della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 84, name: "Maglia Roma Europa League Edition 2022/23", category: "SerieA", categoryLabel: "Serie A", price: 26.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/2223/Roma Special Europa 2223.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della quarta divisa della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 85, name: "Maglia Roma Home da definire", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/Roma.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 86, name: "Maglia Roma Home da definire", category: "SerieA", categoryLabel: "Serie A", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "Vintage", image: "images/3d/Serie A/Roma/Romaa.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta della Roma 1983/84.", kitType: 'solo', inStock: true },
  { id: 87, name: "Pantaloncino Roma Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 10.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Roma/2526/Pant Roma Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "I pantaloncini della Roma 2025/26.", kitType: 'solo', inStock: true },
  // ══════════════ Sassuolo (Serie A) ══════════════
  { id: 88, name: "Maglia Sassuolo Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Sassuolo/2526/Sassuolo Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Sassuolo 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Torino (Serie A) ══════════════
  { id: 89, name: "Maglia Torino Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Torino/2526/Torino Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Torino 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Udinese (Serie A) ══════════════
  { id: 90, name: "Maglia Udinese Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Udinese/2526/Udinese Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Udinese 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ Verona (Serie A) ══════════════
  { id: 91, name: "Maglia Verona Home 2025/26", category: "SerieA", categoryLabel: "Serie A", price: 20.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/Serie A/Verona/2526/Verona Home 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Verona 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // LA LIGA
  // ══════════════════════════════════════

  // ══════════════ REAL MADRID ══════════════
  { id: 95, name: "Maglia Real Madrid Special", category: "LaLiga", categoryLabel: "La Liga", price: 26.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/La Liga/Real Madrid/ChatGPT Image 29 apr 2026, 12_39_32.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special del Real Madrid.", kitType: 'solo', inStock: true },
  { id: 96, name: "Maglia Real Madrid Third 2023/24", category: "LaLiga", categoryLabel: "La Liga", price: 22.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/3d/La Liga/Real Madrid/Real Third 2324.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Real Madrid 2023/24.", kitType: 'solo', inStock: true },

  // ══════════════ ATLETICO MADRID ══════════════
  { id: 97, name: "Maglia Atletico Madrid Home 2025/26", category: ["LaLiga", "Champions"], categoryLabel: ["La Liga", "Champions League"], price: 85.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/atletico_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Atletico Madrid 2025/26.", kitType: 'solo', inStock: true },
  { id: 98, name: "Maglia Atletico Madrid Away 2025/26", category: ["LaLiga", "Champions"], categoryLabel: ["La Liga", "Champions League"], price: 80.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/atletico_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Atletico Madrid 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ PORTO ══════════════
  { id: 99, name: "Maglia Porto Home 2025/26", category: "Champions", categoryLabel: "Champions League", price: 75.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/porto_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Porto 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ MANCHESTER CITY (Premier League) ══════════════
  { id: 100, name: "Maglia Manchester City Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 95.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/mancity_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Manchester City 2025/26.", kitType: 'solo', inStock: true },
  { id: 101, name: "Maglia Manchester City Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 90.00, oldPrice: 105.00, badge: "sale", badgeLabel: "14% OFF", image: "images/teams/mancity_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Manchester City 2025/26.", kitType: 'solo', inStock: true },
  { id: 157, name: "Maglia LucaThird 2025/26", category: "Vintage", categoryLabel: "Vintage", price: 92.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/Nazionali/Germania1990.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia terza divisa Manchester City 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ ARSENAL ══════════════
  { id: 102, name: "Maglia Arsenal Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 92.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/arsenal_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La classica maglia rossa dell'Arsenal 2025/26.", kitType: 'solo', inStock: true },
  { id: 103, name: "Maglia Arsenal Home 2003/04", category: "Vintage", categoryLabel: "Vintage", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "VINTAGE", image: "images/3d/HomeArsenal0304.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La storica maglia casalinga dell'Arsenal 2003/04.", kitType: 'solo', inStock: true },
  { id: 104, name: "Maglia Liverpool Home 2025/26", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 94.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/liverpool_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Liverpool 2025/26.", kitType: 'solo', inStock: true },
  { id: 105, name: "Terza Maglia Liverpool 2025/26", category: "Premier", categoryLabel: "Premier League", price: 88.00, oldPrice: 100.00, badge: "sale", badgeLabel: "12% OFF", image: "images/3d/Premier League/Liverpool Third 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Liverpool 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ CHELSEA ══════════════
  { id: 106, name: "Maglia Chelsea Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 90.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/chelsea_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Chelsea 2025/26.", kitType: 'solo', inStock: true },
  { id: 107, name: "Maglia Chelsea Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 85.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/chelsea_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Chelsea 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ MANCHESTER UNITED ══════════════
  { id: 108, name: "Maglia Manchester United Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 93.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/manutd_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Manchester United 2025/26.", kitType: 'solo', inStock: true },
  { id: 109, name: "Maglia Manchester United Ronaldo 2009", category: "Vintage", categoryLabel: "Vintage", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "VINTAGE", image: "images/3d/Premier League/Ronaldo2009.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La storica maglia del Manchester United indossata da Cristiano Ronaldo nel 2009.", kitType: 'solo', inStock: true },

  // ══════════════ TOTTENHAM ══════════════
  { id: 110, name: "Maglia Tottenham Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 86.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/tottenham_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Tottenham 2025/26.", kitType: 'solo', inStock: true },
  { id: 111, name: "Maglia Tottenham Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 83.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/tottenham_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Tottenham 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ NEWCASTLE ══════════════
  { id: 112, name: "Maglia Newcastle Home 2025/26", category: "Premier", categoryLabel: "Premier League", price: 84.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/newcastle_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Newcastle 2025/26.", kitType: 'solo', inStock: true },
  { id: 113, name: "Maglia Newcastle Away 2025/26", category: "Premier", categoryLabel: "Premier League", price: 81.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/newcastle_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Newcastle 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ NOTTINGHAM FOREST ══════════════
  { id: 114, name: "Terza Maglia Nottingham Forest 2025/26", category: "Premier", categoryLabel: "Premier League", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/3d/terza maglia nottingham forest 2526.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Nottingham Forest 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ BORUSSIA DORTMUND ══════════════
  { id: 115, name: "Maglia Borussia Dortmund Home 2025/26", category: ["Champions", "Bundesliga"], categoryLabel: ["Champions League", "Bundesliga"], price: 88.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/dortmund_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga BVB 2025/26.", kitType: 'solo', inStock: true },
  { id: 116, name: "Maglia Borussia Dortmund Away 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 83.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/dortmund_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta BVB 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ BAYERN MONACO ══════════════
  { id: 117, name: "Maglia Bayern Monaco Away 2007/08", category: "Vintage", categoryLabel: "Vintage", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "VINTAGE", image: "images/3d/HomeBayern0708.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Bayern Monaco 2007/08.", kitType: 'solo', inStock: true },
  { id: 118, name: "Maglia Bayern Monaco Home 2007/08", category: "Vintage", categoryLabel: "Vintage", price: 28.00, oldPrice: null, badge: "vintage", badgeLabel: "VINTAGE", image: "images/3d/HomeBayern0708.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga del Bayern Monaco 2007/08.", kitType: 'solo', inStock: true },

  // ══════════════ BAYER LEVERKUSEN ══════════════
  { id: 119, name: "Maglia Bayer Leverkusen Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 82.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/leverkusen_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Bayer Leverkusen 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ RB LEIPZIG ══════════════
  { id: 120, name: "Maglia RB Leipzig Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 80.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/leipzig_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga RB Leipzig 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ EINTRACHT FRANCOFORTE ══════════════
  { id: 121, name: "Maglia Eintracht Francoforte Home 2025/26", category: "Bundesliga", categoryLabel: "Bundesliga", price: 78.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/eintracht_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Eintracht Francoforte 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ AL NASSR (Saudi Pro League) ══════════════
  { id: 122, name: "Maglia Al Nassr Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 75.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "images/teams/alnassr_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Al Nassr Home 2025/26.", kitType: 'solo', inStock: true },
  { id: 123, name: "Maglia Al Nassr Away 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 70.00, oldPrice: 85.00, badge: "sale", badgeLabel: "18% OFF", image: "images/teams/alnassr_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Al Nassr 2025/26.", kitType: 'solo', inStock: true },
  { id: 124, name: "Maglia Al Nassr CR7 Edition 2025", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 99.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/teams/alnassr_cr7.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione speciale Al Nassr CR7.", kitType: 'solo', inStock: true },

  // ══════════════ AL HILAL ══════════════
  { id: 125, name: "Maglia Al Hilal Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 72.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alhilal_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Hilal 2025/26.", kitType: 'solo', inStock: true },
  { id: 126, name: "Maglia Al Hilal Away 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 68.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alhilal_away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia trasferta Al Hilal 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ AL ITTIHAD ══════════════
  { id: 127, name: "Maglia Al Ittihad Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 70.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alittihad_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Ittihad 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ AL AHLI ══════════════
  { id: 128, name: "Maglia Al Ahli Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 68.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alahli_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Ahli 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════ AL QADSIAH ══════════════
  { id: 129, name: "Maglia Al Qadsiah Home 2025/26", category: "SaudiLeague", categoryLabel: "Saudi Pro League", price: 65.00, oldPrice: null, badge: null, badgeLabel: null, image: "images/teams/alqadsiah_home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia casalinga Al Qadsiah 2025/26.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // NAZIONALI
  // ══════════════════════════════════════

  // ══════════════ Prime 48 in ordine di arrivo allo scorso mondiale ══════════════
  { id: 130, name: "Maglia Home Francia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeFrancia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Francia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 131, name: "Maglia Away Francia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayFrancia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Francia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true},
  { id: 132, name: "Maglia Home Argentina 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeArgentina2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Argentina 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: false },
  { id: 133, name: "Maglia Away Argentina 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayArgentina2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La classica blaugrana del Barcellona 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 134, name: "Maglia Home Spagna 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeSpagna2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Spagna 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 135, name: "Maglia Away Spagna 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwaySpagna2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Spagna 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 148, name: "Maglia Home Inghilterra 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeInghilterra2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Inghilterra 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 149, name: "Maglia Away Inghilterra 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayInghilterra2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta dell'Inghilterra 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 150, name: "Maglia Home Brasile 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeBrasile2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Brasile 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 151, name: "Maglia Away Brasile 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayBrasile2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Brasile 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 152, name: "Maglia Home Marocco 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeMarocco2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Marocco 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 153, name: "Maglia Away Marocco 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayMarocco2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Marocco 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 154, name: "Maglia Home Portogallo 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomePortogallo2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Brasile 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 155, name: "Maglia Away Portogallo 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayPortogallo2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Brasile 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 156, name: "Maglia Home Belgio 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeBelgio2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Belgio 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 157, name: "Maglia Away Belgio 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayBelgio2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Belgio 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 158, name: "Maglia Home Olanda 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeOlanda2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Brasile 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 159, name: "Maglia Away Olanda 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayOlanda2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta dell'Olanda 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 160, name: "Maglia Home Messico 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeMessico2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Messico 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 161, name: "Maglia Away Messico 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayMessico2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Messico 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 162, name: "Maglia Home Colombia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeColombia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Colombia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 163, name: "Maglia Away Colombia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayColombia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Colombia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 164, name: "Maglia Home Germania 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeGermania2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Germania 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 165, name: "Maglia Away Germania 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayGermania2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta della Germania 2026/27.", kitType: 'solo', inStock: true },
  { id: 166, name: "Maglia Home Croazia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeCroazia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Brasile 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 167, name: "Maglia Away Croazia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayCroazia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga della Germania 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 168, name: "Maglia Home Italia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeItalia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Italia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 169, name: "Maglia Away Italia 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayItalia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta dell'Italia 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 170, name: "Maglia Home Usa 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeUsa2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga degli Usa 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 171, name: "Maglia Away Usa 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayUsa2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta degli Usa 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 172, name: "Maglia Home Canada 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeCanada2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Canada 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 173, name: "Maglia Away Canada 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayCanada2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Canada 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 174, name: "Maglia Home Giappone 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/HomeGiappone2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Giappone 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 175, name: "Maglia Away Giappone 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/AwayGiappone2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia da trasferta del Giappone 2026/27.", kitType: 'solo', inStock: true, nascondiMustHave: true },




  // ══════════════ Away 48 in ordine di arrivo allo scorso mondiale ══════════════
  { id: 176, name: "Maglia Special Francia Prematch 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/PreFrancia2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Francia 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
  { id: 177, name: "Maglia Special Argentina Prematch 2026", category: "Mondiale2026", categoryLabel: "Mondiale 2026", price: 24.00, oldPrice: 30.00, badge: "new", badgeLabel: "10% OFF", image: "images/3d/Nazionali/SpecialArgentina2026.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Maglia special Barcellona 2025/26.", kitType: 'solo', inStock: true, nascondiMustHave: true },
    
  // ══════════════ BRASILE ══════════════
  { id: 178, name: "Maglia Brasile Edizione Cristo del Rio", category: "Nazionali", categoryLabel: "Nazionali", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/Cristo Del Rio 2526 .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", shortsProductId: 131, kitType: 'solo', inStock: true },
  { id: 179, name: "Pantaloncini Brasile", category: "Nazionali", categoryLabel: "Nazionali", price: 10.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/pantaloncino cristo del rio.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", kitType: 'solo', inStock: true, display: "none" },
  { id: 180, name: "Canotta Brasile Edizione Cristo del Rio", category: "Nazionali", categoryLabel: "Nazionali", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/canotta brasile cristo.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", shortsProductId: 131, kitType: 'solo', inStock: true },
  { id: 181, name: "Maglia Brasile Edizione Cristo del Rio", category: "Nazionali", categoryLabel: "Nazionali", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/Cristo Del Rio 2526 .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", shortsProductId: 131, kitType: 'solo', inStock: true },
  { id: 182, name: "Pantaloncini Brasile", category: "Nazionali", categoryLabel: "Nazionali", price: 10.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/pantaloncino cristo del rio.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", kitType: 'solo', inStock: true, display: "none" },
  { id: 183, name: "Canotta Brasile Edizione Cristo del Rio", category: "Nazionali", categoryLabel: "Nazionali", price: 22.00, oldPrice: null, badge: "new", badgeLabel: "SPECIALE", image: "images/3d/canotta brasile cristo.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Edizione limitata della maglia del Brasile con il Cristo del Rio. Collezione esclusiva.", shortsProductId: 131, kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // ══════════════════════════════════════
  // COLLEZIONE 2026/27 — SERIE A
  // ══════════════════════════════════════
  { id: 191, name: "Maglia Bologna Home 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Bologna Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bologna 2026/27.", kitType: 'solo', inStock: true },
  { id: 192, name: "Maglia Como Quarta Maglia 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Como Quarta maglia.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La quarta maglia del Como 2026/27.", kitType: 'solo', inStock: true },
  { id: 193, name: "Maglia Inter Away Manica Lunga 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Inter Away (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga della trasferta dell'Inter 2026/27.", kitType: 'solo', inStock: true },
  { id: 194, name: "Maglia Inter Home Manica Lunga 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Inter Home (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga dell'Inter 2026/27.", kitType: 'solo', inStock: true },
  { id: 195, name: "Maglia Inter Third Kit 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Inter Third.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Inter 2026/27.", kitType: 'solo', inStock: true },
  { id: 196, name: "Maglia Juventus Concept 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Juventus concept jersey.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Il concept jersey della Juventus 2026/27.", kitType: 'solo', inStock: true },
  { id: 197, name: "Maglia Juventus Home Manica Lunga 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Juventus Home (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga della Juventus 2026/27.", kitType: 'solo', inStock: true },
  { id: 198, name: "Maglia Milan Away 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Milan Away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Milan 2026/27.", kitType: 'solo', inStock: true },
  { id: 199, name: "Maglia Milan Special 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Milan Special.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale del Milan 2026/27.", kitType: 'solo', inStock: true },
  { id: 200, name: "Maglia Milan Third Kit 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Milan Third .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Milan 2026/27.", kitType: 'solo', inStock: true },
  { id: 201, name: "Maglia Napoli Concept 2026/27", category: "SerieA", categoryLabel: "Serie A", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/serieA/Napoli Concept Jersey.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Il concept jersey del Napoli 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // COLLEZIONE 2026/27 — BUNDESLIGA
  // ══════════════════════════════════════
  { id: 202, name: "Maglia Bayern Monaco Home 2026/27", category: ["Champions", "Bundesliga"], categoryLabel: ["Champions League", "Bundesliga"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Bundesliga/Bayern Monaco Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Bayern Monaco 2026/27.", kitType: 'solo', inStock: true },
  { id: 203, name: "Maglia Bayern Monaco Away 2026/27", category: "Bundesliga", categoryLabel: "Bundesliga", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Bundesliga/Bayern Monaco Away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Bayern Monaco 2026/27.", kitType: 'solo', inStock: true },
  { id: 204, name: "Maglia Borussia Dortmund Home 2026/27", category: ["Champions", "Bundesliga"], categoryLabel: ["Champions League", "Bundesliga"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Bundesliga/Borussia Dortmund Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Borussia Dortmund 2026/27.", kitType: 'solo', inStock: true },
  { id: 205, name: "Maglia Borussia Dortmund Away 2026/27", category: "Bundesliga", categoryLabel: "Bundesliga", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Bundesliga/Borussia Dortmund Away .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Borussia Dortmund 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // COLLEZIONE 2026/27 — LA LIGA
  // ══════════════════════════════════════
  { id: 206, name: "Maglia Atletico Madrid Home 2026/27", category: ["LaLiga", "Champions"], categoryLabel: ["La Liga", "Champions League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/LaLiga/Atletico Madrid Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Atletico Madrid 2026/27.", kitType: 'solo', inStock: true },
  { id: 207, name: "Maglia Barcellona Home 2026/27", category: ["LaLiga", "Champions"], categoryLabel: ["La Liga", "Champions League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/LaLiga/Barcellona Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Barcellona 2026/27.", kitType: 'solo', inStock: true },
  { id: 208, name: "Maglia Barcellona Away 2026/27", category: "LaLiga", categoryLabel: "La Liga", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/LaLiga/Barcellona Away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Barcellona 2026/27.", kitType: 'solo', inStock: true },
  { id: 209, name: "Maglia Real Madrid Home 2026/27", category: ["LaLiga", "Champions"], categoryLabel: ["La Liga", "Champions League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/LaLiga/Real Madrid Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Real Madrid 2026/27.", kitType: 'solo', inStock: true },
  { id: 210, name: "Maglia Real Madrid Third Kit 2026/27", category: "LaLiga", categoryLabel: "La Liga", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/LaLiga/Real Madrid Third Kit .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Real Madrid 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // COLLEZIONE 2026/27 — LIGUE 1
  // ══════════════════════════════════════
  { id: 211, name: "Maglia Lyonnais Home 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Lyonnais Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Lyonnais 2026/27.", kitType: 'solo', inStock: true },
  { id: 212, name: "Maglia Marseille Home 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Marseille Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Marseille 2026/27.", kitType: 'solo', inStock: true },
  { id: 213, name: "Maglia PSG Home 2026/27", category: ["Ligue1", "Champions"], categoryLabel: ["Ligue 1", "Champions League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Psg Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del PSG 2026/27.", kitType: 'solo', inStock: true },
  { id: 214, name: "Maglia PSG Away 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Psg Away .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del PSG 2026/27.", kitType: 'solo', inStock: true },
  { id: 215, name: "Maglia PSG Third Kit 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Psg Third kit.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del PSG 2026/27.", kitType: 'solo', inStock: true },
  { id: 216, name: "Maglia PSG Fourth Kit 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Psg Fourth kit.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La quarta maglia del PSG 2026/27.", kitType: 'solo', inStock: true },
  { id: 217, name: "Maglia PSG Special 2026/27", category: "Ligue1", categoryLabel: "Ligue 1", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Ligue1/Psg Special .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia speciale del PSG 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // COLLEZIONE 2026/27 — PREMIER LEAGUE
  // ══════════════════════════════════════
  { id: 218, name: "Maglia Arsenal Home Manica Lunga 2026/27", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Arsenal Home (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga dell'Arsenal 2026/27.", kitType: 'solo', inStock: true },
  { id: 219, name: "Maglia Arsenal Away Manica Lunga 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Arsenal Away (manica lunga) .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga della trasferta dell'Arsenal 2026/27.", kitType: 'solo', inStock: true },
  { id: 220, name: "Maglia Arsenal Third Kit 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Arsenal Third.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia dell'Arsenal 2026/27.", kitType: 'solo', inStock: true },
  { id: 221, name: "Maglia Aston Villa Home 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Aston Villa Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga dell'Aston Villa 2026/27.", kitType: 'solo', inStock: true },
  { id: 222, name: "Maglia Chelsea Away 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Chealsea Away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Chelsea 2026/27.", kitType: 'solo', inStock: true },
  { id: 223, name: "Maglia Liverpool Home 2026/27", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Liverpool Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Liverpool 2026/27.", kitType: 'solo', inStock: true },
  { id: 224, name: "Maglia Liverpool Away 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Liverpool Away .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Liverpool 2026/27.", kitType: 'solo', inStock: true },
  { id: 225, name: "Maglia Liverpool Home Manica Lunga 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Liverpool Home (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga del Liverpool 2026/27.", kitType: 'solo', inStock: true },
  { id: 226, name: "Maglia Liverpool Third Kit 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Liverpool Third.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Liverpool 2026/27.", kitType: 'solo', inStock: true },
  { id: 227, name: "Maglia Manchester City Home 2026/27", category: ["Champions", "Premier"], categoryLabel: ["Champions League", "Premier League"], price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Manchester City Home .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Manchester City 2026/27.", kitType: 'solo', inStock: true },
  { id: 228, name: "Maglia Manchester City Away 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Manchester City Away.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia della trasferta del Manchester City 2026/27.", kitType: 'solo', inStock: true },
  { id: 229, name: "Maglia Manchester City Home Manica Lunga 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Manchester City Home (manica lunga)ù.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga del Manchester City 2026/27.", kitType: 'solo', inStock: true },
  { id: 230, name: "Maglia Manchester City Third Kit 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Manchester City Third .png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La terza maglia del Manchester City 2026/27.", kitType: 'solo', inStock: true },
  { id: 231, name: "Maglia Manchester United Home Manica Lunga 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Manchester United Home (manica lunga).png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia a manica lunga casalinga del Manchester United 2026/27.", kitType: 'solo', inStock: true },
  { id: 232, name: "Maglia Newcastle Home 2026/27", category: "Premier", categoryLabel: "Premier League", price: 24.00, oldPrice: null, badge: "new", badgeLabel: "Novità", image: "2627/Premier League/Newcastle Home.png", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "La maglia casalinga del Newcastle 2026/27.", kitType: 'solo', inStock: true },

  // ══════════════════════════════════════
  // SCARPE
  // ══════════════════════════════════════

  // ══════════════ NIKE ══════════════
  { id: 136, name: "Nike Mercurial Superfly 10 Elite FG", brand: "Nike", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 89.00, oldPrice: 120.00, badge: "sale", badgeLabel: "26% OFF", image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f566e5e8-3b5b-44ee-b7a0-52e74fb8e6a7/mercurial-superfly-10-elite-fg-football-boot-X0Wdx6.png", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Scarpa da calcio professionale Nike Mercurial Superfly 10 Elite FG. Tomaia Flyknit ultraleggera, tacchetti bladed per massima trazione.", kitType: 'solo', inStock: true },
  { id: 137, name: "Nike Phantom GX II Elite FG", brand: "Nike", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 95.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/60d5a44e-e69f-4d86-b001-2b28a6bbf3ef/phantom-gx-ii-elite-fg-football-boot-V8KFRX.png", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Nike Phantom GX II Elite FG — il tocco di palla più preciso della gamma Nike. Tomaia Gripknit e zona strike asimmetrica.", kitType: 'solo', inStock: true },
  { id: 138, name: "Nike Air Zoom Pegasus 41", brand: "Nike", category: "Scarpe", categoryLabel: "Running", price: 75.00, oldPrice: null, badge: null, badgeLabel: null, image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1e9e4e9c-6f0b-4ff6-a5b7-0e99e9f4d5a4/air-zoom-pegasus-41-road-running-shoes-zx37fC.png", sizes: ["39", "40", "41", "42", "43", "44", "45", "46"], description: "Nike Air Zoom Pegasus 41 — ammortizzazione reattiva con unità Air Zoom per ogni lunghezza di passo. Il classico versatile per il running.", kitType: 'solo', inStock: true },

  // ══════════════ ADIDAS ══════════════
  { id: 139, name: "Adidas Predator Elite FG", brand: "Adidas", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 92.00, oldPrice: 130.00, badge: "sale", badgeLabel: "29% OFF", image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/3e3f4d2a5d364b1d9a2faf3800bf71c5_9366/Predator_Elite_Firm_Ground_Boots_Black_IG5459_01_standard.jpg", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Adidas Predator Elite FG — zone Controlskin sulla tomaia per un tocco di palla migliorato e potenza di tiro superiore.", kitType: 'solo', inStock: true },
  { id: 140, name: "Adidas Copa Pure II Elite FG", brand: "Adidas", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 85.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/3a5b2c4d6e374c1e8b3fag4900cg82d6_9366/Copa_Pure_II_Elite_FG_Boots_White_HQ8987_01_standard.jpg", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Adidas Copa Pure II Elite FG — tomaia in pelle premium per il massimo feeling palla. La scelta del centrocampista.", kitType: 'solo', inStock: true },
  { id: 141, name: "Adidas Ultraboost 5.0 Running", brand: "Adidas", category: "Scarpe", categoryLabel: "Running", price: 80.00, oldPrice: null, badge: null, badgeLabel: null, image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/ultraboost-5-shoes-white_GY2354_01_standard.jpg", sizes: ["39", "40", "41", "42", "43", "44", "45", "46"], description: "Adidas Ultraboost 5.0 — intersuola Boost per un ritorno di energia ottimale ad ogni passo. Il top del comfort per il running.", kitType: 'solo', inStock: true },

  // ══════════════ PUMA ══════════════
  { id: 142, name: "Puma Future 7 Ultimate FG/AG", brand: "Puma", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 78.00, oldPrice: 110.00, badge: "sale", badgeLabel: "29% OFF", image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/107783/01/sv01/fnd/PNA/fmt/png/FUTURE-7-ULTIMATE-FG/AG-Men's-Football-Boot", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Puma Future 7 Ultimate FG/AG — calza AdaptiveFit che avvolge il piede come un guanto. Tacchetti ibridi per erba naturale e sintetica.", kitType: 'solo', inStock: true },
  { id: 143, name: "Puma King Ultimate FG/AG", brand: "Puma", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 82.00, oldPrice: null, badge: null, badgeLabel: null, image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/107343/01/sv01/fnd/PNA/fmt/png/KING-ULTIMATE-FG/AG-Men's-Football-Boot", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Puma King Ultimate — l'icona del calcio. Pelle di canguro premium per un tocco ineguagliabile.", kitType: 'solo', inStock: true },

  // ══════════════ NEW BALANCE ══════════════
  { id: 144, name: "New Balance Furon v7+ Pro FG", brand: "New Balance", category: "Scarpe", categoryLabel: "Scarpe da calcio", price: 72.00, oldPrice: 95.00, badge: "sale", badgeLabel: "24% OFF", image: "https://nb.scene7.com/is/image/NB/msf1fp77_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "New Balance Furon v7+ Pro FG — tomaia Hypoknit ultra-leggera per velocità esplosiva. Perfetta per i giocatori d'attacco.", kitType: 'solo', inStock: true },
  { id: 145, name: "New Balance Fresh Foam X 1080 v13", brand: "New Balance", category: "Scarpe", categoryLabel: "Running", price: 85.00, oldPrice: null, badge: "new", badgeLabel: "NUOVO", image: "https://nb.scene7.com/is/image/NB/m1080l13_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440", sizes: ["39", "40", "41", "42", "43", "44", "45", "46"], description: "New Balance Fresh Foam X 1080 v13 — massima ammortizzazione per le lunghe distanze. L'intersuola Fresh Foam X offre comfort senza precedenti.", kitType: 'solo', inStock: true },

  // ══════════════ LIFESTYLE ══════════════
  { id: 146, name: "Nike Air Force 1 '07", brand: "Nike", category: "Scarpe", categoryLabel: "Lifestyle", price: 65.00, oldPrice: null, badge: null, badgeLabel: null, image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes-WrLlWX.png", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Nike Air Force 1 '07 — il classico senza tempo. Tomaia in pelle con ammortizzazione Air-Sole per tutto il giorno.", kitType: 'solo', inStock: true },
  { id: 147, name: "Adidas Samba OG", brand: "Adidas", category: "Scarpe", categoryLabel: "Lifestyle", price: 70.00, oldPrice: null, badge: "new", badgeLabel: "TREND", image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/2b4a3b5c7f384d2f9c4gbg5a10dh93e7_9366/Samba_OG_Shoes_White_B75806_01_standard.jpg", sizes: ["39", "40", "41", "42", "43", "44", "45"], description: "Adidas Samba OG — iconico dal 1949. Tomaia in pelle con T-toe in pelle scamosciata. Il modello più richiesto dello streetwear.", kitType: 'solo', inStock: true },

];
